version: '3.7'

x-api-environment:
  &api-environment
  environment:
    - PORT=80
    - APP_ENV=development
    - APP_CONFIG=config.development
    - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
  build:
    context: ./api
    dockerfile: Dockerfile
  volumes:
    - type: bind
      source: ./api
      target: /app
  depends_on:
    - postgres

x-frontend-environment:
  &frontend-environment
  environment:
    - HOST=0.0.0.0
    - PORT=80
    - NODE_ENV=development
    - WEBSITE_ORIGIN=http://0.0.0.0:9000
    - API_URL=http://0.0.0.0:8000/api/
  build:
    context: ./frontend
    dockerfile: Dockerfile
  volumes:
    - type: bind
      source: ./frontend/src
      target: /app/src
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:alpine

  api:
    <<: *api-environment
    restart: always
    image: api
    ports:
      - "8000:80"
    command: /start-reload.sh

  frontend:
    <<: *frontend-environment
    restart: always
    image: frontend
    ports:
      - "9000:80"
    command: yarn dev