runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app-single:server

runtime_config:
  python_version: 3

api_version: 1
threadsafe: true

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  instance_tag: gae
  name: caeduscovid-sharedservice-vpc
  subnetwork_name: subnet-us-east1

handlers:
- url: /.*
  script: auto
  secure: always
